### ISSUE TITLE
US1 - Display trip preview cards

### ISSUE THREAD

**Issue by LukasWeckner** [LukasWeckner/Capstone-Travel#1]
## Value Proposition

**As a** User
**I want to** have an overview of my upcoming vacation trips
**so that** I am able to prepare for them in time.
​

## Description
<img width="298" alt="Screenshot 2023-06-16 at 14 37 44" src="https://github.com/LukasWeckner/Capstone-Travel/assets/130902818/a5682cfa-1cd0-4c4b-8de6-dd1428f3819c">

## Acceptance Criteria

- [ ] The page has a heading called "Current trips"
- [ ] The trips are displayed among each other
- [ ] Each trip is displayed in it's own card
- [ ] Every card contains the name of the trips destination as a heading
- [ ] Every card contains the start date for the trip
- [ ] Every card contains the end date for the trip
      ​

## Tasks

- [ ] Open branch "feature/display-trip-previews"
- [ ] Create mock data array
- [ ] Create Component `PreviewCard`
- [ ] Map over the the mock data array in `PreviewCard`
- [ ] Return the destination within `PreviewCard`
- [ ] Return the start date as string within `PreviewCard`
- [ ] Return the end date as string within `PreviewCard`

**Comment by RonnySteady** [comment]
LGTM - just one question/suggestion:
- Day title 1 seems to become Heading 1 after saving, maybe you could use the same names to make in both screens

**Comment by FelineHuhn** [comment]
Hey Lukas, nice start! 🎉 I have only some tiny suggestions. 

I ask me if it maybe would be cool, to use mock data in a first way, to display some example trips in the list, so the app is not that empty, when you try it out!? If you would use mock data, it would be a second idea, that you could split the user story into two, one for the trip list and the second for adding a new trip.... 

Also it would be very nice, when you picture realistic data in your wireframes instead of "Heading 1" and "Activity content..." to make your feature more clearly. 

I like the acceptance criteria, you only forgot to mention the headline. And I ask me if the day title input is a date picker? An can you submit the form, when an input field is still empty? You could mention that in the acceptance criteria too. 

To your tasks:Maybe it could be a little bit more specific, like mentioning the form and input fields too. And I would prefer another branch name (not in camel case) like feature/create-trip or something like that. The `Day` component could also be more descriptive maybe like `TripDay`, or? Also the headline could be mention as a task.

**Comment by LukasWeckner** [comment]
@FelineHuhn 
Thanks for the feedback!

It took some time but I took most of your advice and decided to split the user story i wrote in the first place and make 2 stories out of it. 
I also decided that I even need a different user story as my first user story which you can see here now :)

My first user story only displays an overview of upcoming trips with a few basic information. In the next US i want to add a details page for every trip, where the single days for the trip are displayed with the corresponding activities (also with mock data). 

Creating a new trip will be shifted to US3.

**Comment by FelineHuhn** [comment]
Really nice progress and I think your decision of the new user stories is great. 🎉 Just some last tiny suggestions, but it's not that important, more a taste of matter: 

I personally think the wording "card" would be more suitable than "box". And you could be a little bit less specific in the tasks, than you are more flexible in some points, or? And the acceptance criteria could be less technical, the technical part is the task section.

**Comment by LukasWeckner** [comment]
Thanks! :)
Adjusted the US a little more with your suggestions 🪛
