### ISSUE TITLE
US6: Header Component

### ISSUE THREAD

**Issue by LukasWeckner** [LukasWeckner/Capstone-Travel#11]
## Value Proposition

**As a** User
**I want to** always see the title of the page I am currently on  
**so that** I immediately know what the purpose of the page is
​

## Description
Header with a heading for each page
![US6](https://github.com/LukasWeckner/Capstone-Travel/assets/130902818/0a4801e3-bf15-4b2a-8977-534a6f35ea9e)
​

## Acceptance Criteria

- [ ] Every page of the app needs to have a heading
- [ ] The headings need to be centered on the page
- [ ] The heading of the "My trips" page is "My trips"
- [ ] The heading of the "New trip" page is "New trip"
- [ ] The headings are not hard coded but displayed with a Header component
- [ ] The Header component can have more content than a heading, but it's not required
      ​

## Tasks

- [ ] Create branch `feature/header-component`
- [ ] Delete all hard coded headings
- [ ] Create Header component
    - [ ] return at least an h1
    - [ ] props: `heading` (text of h1)
- [ ] Display Header on all pages of the app
- [ ] Declare a value for the `heading` props on each page

**Comment by dimitriosxmi** [comment]
## LGTM ✅ 
Notes: Very clear and straight forward! I fully understood everything 😄

**Comment by CarstenJahnke** [comment]
good work! I like to see where your app is going 👍
