### ISSUE TITLE
US7: Dynamic trip duration

### ISSUE THREAD

**Issue by LukasWeckner** [LukasWeckner/Capstone-Travel#12]
## Value Proposition

**As a** User  
**I want to** i want to have a form with the right amount of days for my trip when adding a new trip 
**so that** I can plan each day of my trip
​

## Description
<img width="378" alt="US7" src="https://github.com/LukasWeckner/Capstone-Travel/assets/130902818/d6ba9e7c-471c-4f98-af5e-435dbd39807e">
​

## Acceptance Criteria

- [ ] The End date of the trip cannot be an earlier date than the Start date
- [ ] The form for a New Trip displays the correct amount of Trip Days according to the provided `Start date` and `End date` of the trip. E.g. Start date: 01/07/2023 , End Date: 04/07/2023 --> 4 Trip day Cards are being displayed in the form
- [ ] When changing the Start or End date, the form directly updates the amount of displayed trip days
- [ ] The fields `Start date` and `End date` are required to be filled
- [ ] Data for the Trip Days is not required to submit the form
- [ ] After submitting the form the details page of the freshly created trip opens up
- [ ] The details page displays as many Trip Day cards as displayed in the New Trip form
      ​

## Tasks

- [ ] Create branch `feature/dynamic-trip-duration`
- [ ] Write functionality which disables user to pick an End date which is earlier than the Start date of the trip
- [ ] Create event handler for changing start date or end date
- [ ] Write function to calculate the trip duration in days
- [ ] Display the amount of trip day cards equal to the trip duration in days
- [ ] Set attribute `required` for Start date and End Date fields
- [ ] Remove attribute `required` for the fields of the Trip Day cards

**Comment by dimitriosxmi** [comment]
## LGTM
Nicely detailed and finely written imo a fine User Story you got here going 😊
