### ISSUE TITLE
US8: Sort overview page "My trips" by date

### ISSUE THREAD

**Issue by LukasWeckner** [LukasWeckner/Capstone-Travel#13]
## Value Proposition

**As a** user 
**I want to** have the previews of my trips sorted in a way that the upcoming trip is shown first
**in order to**  immediately see the most recent upcoming trips
​

## Description
<img width="372" alt="US8" src="https://github.com/LukasWeckner/Capstone-Travel/assets/130902818/ef12fb53-a6ea-4b0f-922a-762649878682">
​

## Acceptance Criteria

- [ ] The trip preview with the earliest Start date is shown first
- [ ] All other previews follow the same logic --> the second trip preview has the second earliest Start date and so on
- [ ] When adding a new trip, it is placed on the correct position on the trip preview page according to it's Start date
      ​

## Tasks

- [ ] Create branch `feature/sort-preview-page`
- [ ] Add sort method to the map method of the array which is used to display all trip previews
- [ ] Figure out how to sort by the Start date as it is just a string in the array

**Comment by dimitriosxmi** [comment]
Superb, simple and on point! lgtm 😄
