### ISSUE TITLE
US9: Implement delete button

### ISSUE THREAD

**Issue by LukasWeckner** [LukasWeckner/Capstone-Travel#14]
## Value Proposition

**As a** User 
**I want to** be able to delete trips I no longer need  for whatever reason
**so that** I only see information about the trips I actually want to see
​

## Description
Clicking the delete button deletes the trip
<img width="697" alt="US9" src="https://github.com/LukasWeckner/Capstone-Travel/assets/130902818/7126519a-2cd4-477b-888b-87fa45804bcb">
​

## Acceptance Criteria

- [ ] Each `PreviewCard` of the `My trips` page has a delete button 
- [ ] Clicking the delete button deletes the trip from the My Trips page
- [ ] Clicking the delete button also deletes the trip details of the trip, so that it can't be accessed by the path `/my-trips/[slug]` anymore (e.g /my-trips/paris)
- [ ] The delete button has a red color
- [ ] For now the users confirmation to delete a trip after clicking the delete button is not required
      ​

## Tasks

- [ ] Create branch `feature/implement-delete-button`
- [ ] Create `Button` Component
- [ ] Props: `onClick`, `children`(button text) 
- [ ] Display `Button` on each `PreviewCard`
- [ ] Write function for deleting trips
- [ ] Pass prop values from `PreviewCard` to `Button`
- [ ] Create and apply StyledComponent to display Button with red background color

**Comment by dimitriosxmi** [comment]
In my opinion that's a very clear and easy to understand and follow User Story 💯 😄 👍 GJ!
