### ISSUE TITLE
US10: Edit trip

### ISSUE THREAD

**Issue by LukasWeckner** [LukasWeckner/Capstone-Travel#15]
## Value Proposition

**As a** User 
**I want to** be able to edit the trips I have created
**so that** I can keep the information for my trips up to date if anything changes
​

## Description
<img width="699" alt="US10" src="https://github.com/LukasWeckner/Capstone-Travel/assets/130902818/bba2d3ac-4e8d-48de-977f-7a2797411d9e">

​

## Acceptance Criteria

- [ ] Each `Trip Details` page displays an `Edit` button
- [ ] Clicking the Edit button redirects the user to an `Edit trip` page
- [ ] The Edit trip page displays the data of the trip the user wants to edit in a form
- [ ] All the data in the form is editable by the user
- [ ] The form displays a `Save` button and a `Cancel` button
- [ ] Clicking the Cancel button redirects the user back to the detail page of the trip without making any changes
- [ ] Clicking the Save button updates the information of the trips details page according the changes made inside the form and redirects the user back to the details page of his trip
- [ ] Clicking the Save button on the Edit Page also updates the PreviewCard (City, start date, end date) of the trip on the 
       `My trips` page if any changes were made
      ​

## Tasks

- [ ] Create branch `feature/edit-trip`
- [ ] Display Edit button on each details page
- [ ] Create `Edit Trip` page
- [ ] Use `NewTripForm` component to display form on Edit Trip page
- [ ] Prefill the Edit Trip form with the data of the trip details
- [ ] Add a Save and a Cancel button to the Edit Trip page
- [ ] Write handler function for the Save button
- [ ] Write handler function for the Cancel button

**Comment by julialoeschel** [comment]
🚀  lgtm!
