### ISSUE TITLE
US11: Implement local storage

### ISSUE THREAD

**Issue by LukasWeckner** [LukasWeckner/Capstone-Travel#16]
## Value Proposition

**As a** User 
**I want to** be able to save my trips permanently in my app 
**so that** they are not deleted after refreshing or closing my app
​

## Description
<img width="681" alt="US11" src="https://github.com/LukasWeckner/Capstone-Travel/assets/130902818/166de05f-ebd0-4bce-a7a4-1ff6042b1be5">

​

## Acceptance Criteria

- [ ] After creating a new trip and refreshing the page or closing and reopening the app, the preview of the new trip is still displayed 
       on the `My Trips` page
- [ ] The first criteria is also true for the details page of the trip (click button `Show Details` to check)
      ​

## Tasks

- [ ] Create branch `feature/local-storage`
- [ ] Save new trip data to the local storage within the handleSubmit of the NewTripForm component
- [ ] Save edited trip data to the local storage
- [ ] Display trip data on `My trips` page and details pages based on local storage data
- [ ] Remove mock data array

[US3: Add new trip](https://github.com/LukasWeckner/Capstone-Travel/issues/3)
[US10: Edit trip](https://github.com/LukasWeckner/Capstone-Travel/issues/15)

**Comment by ghost** [comment]
LGTM 🚀
