### ISSUE TITLE
US2 - Display trip details

### ISSUE THREAD

**Issue by LukasWeckner** [LukasWeckner/Capstone-Travel#2]
## Value Proposition

**As a** User  
**I want to** be able to see the detailed information for each of my trips
**so that** I can look forward to every single day of my vacation.
​

## Description
The left wireframe was mostly created in the previous user story. Only the blue bordered button is added here.

Clicking the "Show Details" button opens the "Trip Details" page for each trip

<img width="678" alt="US2" src="https://github.com/LukasWeckner/Capstone-Travel/assets/130902818/bbcfe12b-3913-4766-aa22-723217579e48">

​

## Acceptance Criteria

- [ ] Each card of `Current trips` page displays a button `Show details`
- [ ] Clicking the button opens the `Trip details` page (right wireframe) for the corresponding trip
- [ ] The details page has a heading on top of the page
- [ ] Below the heading one can see the destination, the start and the end date of the trip
- [ ] For each day of the trip there is a heading (e.g Day 1: Arrival) and information about the activities of the day
- [ ] The days are displayed one below the other
      ​

## Tasks

- [ ] Create branch `feature/display-trip-details`
- [ ] Create `Button` component
- [ ] Add `Button` to `PreviewCard` component
- [ ] Write handleFunction for button click and pass it to the button
- [ ] Create dynamic details page `pages/current-trips/[slug]`
- [ ] Find correct trip (slug) with useRouter
- [ ] Use next/Link to link to the details page of a trip
- [ ] Create component `TripDay`
- [ ] Display the trip days and their activities as a list
- [ ] Display content from mock data array and `TripDay` component on details page

**Comment by nastiche** [comment]
Hi Lukas,

eine sehr romantische Value Proposition hast du da..."so that I can look forward to every single day of my vacation." )))

ich würde den zweiten Satz deiner Value Proposition ein bisschen kürzer machen, z.B. "I want to be able see the detailed information for each trip"... Weil du hast ja "overview of my trips" schon in der US1 gemacht, daher musst du es nicht nochmal erwähnen.

Sonst finde ich die US mega gut und schön detailliert.

Nasti
