### ISSUE TITLE
US12 - Implement openAI API

### ISSUE THREAD

**Issue by LukasWeckner** [LukasWeckner/Capstone-Travel#23]
## Value Proposition

**As a** User
**I want to** to get suggestions for activities in the city I want to go to
**so that** I don't have to do all the research about attractions on my own
​

## Description
<img width="631" alt="US12" src="https://github.com/LukasWeckner/Capstone-Travel/assets/130902818/ff27b1b4-8b2a-4296-b17b-6064babc13b2">

​

## Acceptance Criteria

- [ ] The app has a new page called `Idea Generator` which can be accessed in the footer navigation
- [ ] On the top of the new page there is text telling the user what he needs to do to use the idea generator AI
- [ ] Below this explanation text there is a form with the fields `Destination`, `Start date` and `End date`
- [ ] The `Destination` field accepts text value and doesn't take more than 25 characters
- [ ] The `Start Date` and `End Date` fields offer a date picker function
- [ ] All three fields are required to be filled
- [ ] A button with the text "Generate"is displayed on the bottom of the form
- [ ] After submitting (Clicking "Generate") the user is being forwarded to a `Trip Details` page which displays the data the user provided in the 3 fields of the form and data for each day of his trip (a day title and activities) which were created by the AI.
- [ ] The `Details Page` has the same structure like other details pages which were manually (without AI Idea Generator) created by the user.
      ​

## Tasks

- [ ] Create branch `feature/implement-openAI`
- [ ] Create new `Idea Generator` page with explanation text for the user
- [ ] Create form within the idea generator page
- [ ] Add Idea Generator page to the footer navigation
- [ ] Implement openAI API and check if I can get a response from it being displayed on my page
- [ ] Write prompts for the AI how it has to create the trip data
- [ ] Include the form field values of destination, start date and end date in the prompts for the AI
- [ ] Let the complete trip data be displayed on details page after clicking "Generate"

**Comment by ghost** [comment]
a cool idea. I
I can vividly imagine how this feature works, and I can also easily understand your approach. Great job! (I have no clue how difficult it could it be to write a prompt that highlights special events at the destination during the travel dates (city festivals, concerts, etc.), but that would be an awsome feature as well, maybe a bonus ;-) )
