### ISSUE TITLE
US13 - Styling trips pages

### ISSUE THREAD

**Issue by LukasWeckner** [LukasWeckner/Capstone-Travel#25]
## Value Proposition

**As a** User 
**I want to** have well styled pages where my trips are being displayed
**so that** I enjoy planning my trips more.
​

## Description
The landing page "My Trips" displays preview cards for all trips which are planned.
By clicking the button "Show Details" on a preview card you get to a details page for each trip.

Both pages "My Trips" and the dynamic "Trip Details" page shall receive an appealing styling.
​

## Acceptance Criteria

- [ ] The pages make use of at least one color which is not black/white/grey
- [ ] All text content is well readable and therefore accessible
- [ ] The page elements got enough space around each other (e.g. no text directly next to a border)
- [ ] Elements are somehow aligned with each other (not all over the place)
      ​

## Tasks

- [ ] Create branch `styling/trip-data`
- [ ] Define and use provisional color palette
- [ ] Check for accessibility regarding readability
- [ ] Rearrange elements of page
- [ ] Edit and create StyledComponents

**Comment by matschi3** [comment]
oh ,another style US :)
well written, looks good 🚀

**Comment by CarstenJahnke** [comment]
LGTM 👍
