### ISSUE TITLE
US14: Styling pages with forms

### ISSUE THREAD

**Issue by LukasWeckner** [LukasWeckner/Capstone-Travel#26]
## Value Proposition

**As a** user
**I want to** have well styled and structured pages when entering my data
**so that** I can easily understand where to put which information and enjoy the process of doing so
​

## Description
The app got three pages where formulars are being used:
- Idea Generator page
- New Trip page
- Edit Trip page (to access navigate to a trips details page and click edit button)

These three pages shall be styled to match the style of the "My Trips" and "Trip Details" pages.
Especially for the forms an important goal is to let them be as easy as possible to understand through styling and layout.
​

## Acceptance Criteria

- [ ] The mentioned form pages use the same color scheme as "My Trips" and "Trip Details" pages
- [ ] To a user it is clear what information he/she needs to put inside the forms
- [ ] All page elements got enough space around each other (e.g. no text directly next to a border)
- [ ] All text content is well readable and therefore accessible
      ​

## Tasks

- [ ] Create branch `styling/form-pages`
- [ ] Apply same color scheme as to "My Trips" and "Trip Details" pages
- [ ] Adjust the spacing and layout of form fields
- [ ] Check for accessibility regarding readability
- [ ] Edit and create styled components if necessary

**Comment by dimitriosxmi** [comment]
## LGTM great US quite clear and understandable!
Note: hope you manage to pull through the styling sooner than expected 😊
