### ISSUE TITLE
US15: Fetch loading screen

### ISSUE THREAD

**Issue by LukasWeckner** [LukasWeckner/Capstone-Travel#28]
## Value Proposition

**As a** user
**I want to** see a loading page while the AI generates the data for my trip
**so that** I know the loading still takes time and everything is fine with my browser
​

## Description
<img width="955" alt="US15" src="https://github.com/LukasWeckner/Capstone-Travel/assets/130902818/07788252-e38c-4dd2-a528-ef82ca498fac">

​

## Acceptance Criteria

- [ ] After clicking the `Generate` button on the idea generator page, the screen displays information that a new trip is being generated
- [ ] When the fetch is done, the information disappears and the user gets redirected to the "Trip Details" page of the new trip
      ​

## Tasks

- [ ] Create branch `feature/loading-screen`
- [ ] Decide what should be displayed as loading screen
- [ ] Create the loading page
- [ ] Integrate display of loading page into the handleSubmit function of the form
- [ ] Make sure that the user gets redirected as soon as the data fetching is completed
