### ISSUE TITLE
US3 - Add new trip

### ISSUE THREAD

**Issue by LukasWeckner** [LukasWeckner/Capstone-Travel#3]
## Value Proposition

**As a** User
**I want to** be able to add a new trip to my current trips
**in order to** to plan my future trips.
​

## Description
After submitting the form the users gets a message that his data was saved. Displaying the data will be covered in the next US.

![US3](https://github.com/LukasWeckner/Capstone-Travel/assets/130902818/7879ec69-8527-4645-9d8b-5896c77f1b9d)

​

## Acceptance Criteria

- [ ] The page has a heading
- [ ] All data gets collected in one form
- [ ] Submitting the form successfully triggers a confirmation message
- [ ] All fields of the form are required to be filled
- [ ] The input field `Destination` is displayed and excepts text value
- [ ] The input field `Start date` is displayed and offers a date picker function
- [ ] The input field `End date` is displayed and offers a date picker function
- [ ] Below `End Date` there is a subheading for the single days of the trip
- [ ] The input field `Day title` is displayed and excepts text value
- [ ] The textarea field `Activities` is displayed and excepts text value
- [ ] The fields `Day title` and `Activities` are grouped together in a card 
- [ ] This card gets displayed 5 times by default
      ​

## Tasks

- [ ] Create branch `feature/add-new-trip`
- [ ] Create component `NewTripForm` with the fields described in the Acceptance Criteria
- [ ] Create component `NewTripDay` with the fields `Day title` and `Activities`
- [ ] Display `NewTripDay` in `NewTripForm` 5 times (default)
- [ ] Use existing `Button` component to display the submit button
- [ ] Write function for Submit Button to display a confirmation message

**Comment by ghost** [comment]
Nice Userstory, very easy to understand!
I would approve it right away, with only one note.^^
Keep in mind to adjust your default `day title` and `activities` card, so if you plan a trip over 3 days, there is no need to display those cards 5 times :)
But for now it is completely fine, I guess!

**Comment by LukasWeckner** [comment]
Thanks :)

Yea for sure, later on I will add a field for the trip duration in days and only render as many days as the user needs for the trip.
