### ISSUE TITLE
US16: Delete Confirmation

### ISSUE THREAD

**Issue by LukasWeckner** [LukasWeckner/Capstone-Travel#31]
## Value Proposition

**As a** User
**I want to** be asked if I really want to delete a trip after clicking the delete button 
**so that** I don't accidentally delete a trip I don't want to delete 
​

## Description
Clicking the delete button opens a pop-up where the user can decide if he wants to delete the trip or not
<img width="636" alt="US16" src="https://github.com/LukasWeckner/Capstone-Travel/assets/130902818/14982394-7fd0-41fc-9220-6970b8a097e2">

​

## Acceptance Criteria

- [ ] Clicking the delete button (icon) of a trip opens a pop-up window with the question if a user wants to delete this trip
- [ ] The pop-up window also displays a "Yes" and a "No" button next to each other like in the picture
- [ ] Clicking the "No" button closes the pop-up window and nothing else happens
- [ ] Clicking the "Yes" button deletes the trip for which the user pressed the delete button (icon)
- [ ] After the deletion the pop-up window closes and the updated "My Trips" page, without the deleted trip, is displayed
      ​

## Tasks

- [ ] Create branch `feature/delete-confirmation`
- [ ] Create a component for the modal (pop-up window)
- [ ] Write the logic for displaying the modal
- [ ] Adapt the deleting logic according to the modal
- [ ] Style the modal component according to the design of the rest of the app

**Comment by RonnySteady** [comment]
Looks perfect 🚀
