### ISSUE TITLE
US17: Landing page

### ISSUE THREAD

**Issue by LukasWeckner** [LukasWeckner/Capstone-Travel#34]
## Value Proposition

**As a** User
**I want to** to see some information when I open the app and have not added any trips yet 
**so that** I know where to go in the app to get started to plan my trips
​

## Description
When there are no trips created yet instead of an empty screen a welcome page with first steps is being displayed
<img width="289" alt="Screenshot 2023-07-10 at 07 27 05" src="https://github.com/LukasWeckner/Capstone-Travel/assets/130902818/51103ab5-d67c-423c-a722-e054da79e925">

​

## Acceptance Criteria

- [ ] If the user did not create any trips yet, an info text saying that there are no trips yet is being displayed
- [ ] Below the info text the user is given the two options from the description to proceed in creating his first trip
- [ ] Both options are displayed in a box
- [ ] Clicking each box links to the appropriate page just like the footer navigation does
      ​

## Tasks

- [ ] Create branch `feature/landing-page`
- [ ] Create logic to display info text when there are not trips created yet
- [ ] Write the content which shall be displayed in this case
- [ ] Add link functionality to the boxes with the proceeding options
- [ ] Style the new content according to the rest of the app

**Comment by MariaRiosNavarro** [comment]
LGTM🚀 go Lukas go!!
