### ISSUE TITLE
US4: Footer navigation

### ISSUE THREAD

**Issue by LukasWeckner** [LukasWeckner/Capstone-Travel#4]
## Value Proposition

**As a** User
**I want to** have a footer navigation
**so that** I am able to easily navigate through the app
​

## Description
![Screenshot 2023-06-19 at 14 35 39](https://github.com/LukasWeckner/Capstone-Travel/assets/130902818/8e9771d8-202a-480d-b95c-732e02ead1e3)

​

## Acceptance Criteria

- [ ] Every page of the app displays a navigation footer with the navigation items `My trips` and `New trip`
- [ ] The navigation items have to be displayed either as text or as text with an icon. Only an icon is not enough.
- [ ] The navigation item of the page a user is currently on has to be visually highlighted (see second wireframe)
- [ ] When a user is on a details page of a trip, the `My trips` navigation item is highlighted
- [ ] Both navigation items are clickable
- [ ] Each navigation item navigates to the page according to its name
      ​

## Tasks

- [ ] Create branch `feature/create-footer-navigation`
- [ ] Create component `FooterNavigation` with the navigation items `My trips` and `New trip`
- [ ] Add FooterNavigation to all pages
- [ ] Create styled component for FooterNavigation
- [ ] Additionally create an active state for the active navigation items
- [ ] Apply the styled component and active where it is needed
- [ ] Add Links to both navigation items linking to the pages according to their name

**Comment by actyvystom** [comment]
A nice one! 🙂 
Anyway a few comments: as you are also mentioning the **New trip** navigation item in either wireframe and task list, you should also pick it up in your acceptance criteria (e.g. both items are clickable and navigate the user to xyz) and also add the linking of both to your task list. 
In other words: what's a navigation bar without navigation functionality? 😉

**Comment by LukasWeckner** [comment]
> 

Thanks Thomas :)

Definitely a more than valid point :D Thanks to you the nav bar will not only look good but also work ;-)
