### ISSUE TITLE
US5: Display new trip data

### ISSUE THREAD

**Issue by LukasWeckner** [LukasWeckner/Capstone-Travel#5]
## Value Proposition

**As a** User
**I want to** see the new trip I created
**so that** the overview of my trips and their details are displayed completely
​

## Description
A new trip to Paris was created with the `NewTripForm` of US3. The new trip is displayed on the `My trips` page and has a Details page just like the other (mock data) entries. The mock data entries will be kept in the app for now.

![US5](https://github.com/LukasWeckner/Capstone-Travel/assets/130902818/d7a22aee-cec6-47a7-9737-2d7a0973f315)

​

## Acceptance Criteria

- [ ] The `My trips` page displays a preview of the new trip like it does for the other mock data entries
- [ ] Clicking the show details button opens the `Trip details` page for the new trip
- [ ] All data which were put into the `NewTripForm` are displayed on the two pages referenced in the previous acceptance criteria
      ​

## Tasks

- [ ] Create branch `feature/display-new-trip-data`
- [ ] Access the data from the `NewTripForm`
- [ ] Add the data for the new trip to the mock array which is used to display all trips
